#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiuX.LogPanel.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Views\Home\Basic.cshtml"
    using NiuX.LogPanel.Views;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Basic : NiuX.LogPanel.Views.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");




            
            #line 5 "..\..\Views\Home\Basic.cshtml"
  
    Layout = new _layout {Context = Context, Section = { ["Scripts"] = $"<script src='{Context.Options.PathMatch}/js.basic.js'></script>" }, ViewData = ViewData };


            
            #line default
            #line hidden
WriteLiteral("<div class=\"card\">\r\n    <div class=\"card-header border border-top-0 border-right-" +
"0 border-left-0\">\r\n        日志\r\n    </div>\r\n    <div class=\"card-body\">\r\n        " +
"<form>\r\n            <div class=\"row\">\r\n                <div class=\"col-md-3\">\r\n " +
"                   <div class=\"form-group\">\r\n                        <div class=" +
"\"custom-control custom-checkbox\">\r\n                            <input type=\"chec" +
"kbox\" class=\"custom-control-input\" id=\"all\">\r\n                            <label" +
" class=\"custom-control-label\" for=\"all\" style=\" position: initial;\">所有</label>\r\n" +
"                        </div>\r\n                    </div>\r\n                </di" +
"v>\r\n                <div class=\"col-md-3\">\r\n                    <div class=\"form" +
"-group\">\r\n                        <div class=\"custom-control custom-checkbox\">\r\n" +
"                            <input type=\"checkbox\" class=\"custom-control-input\" " +
"id=\"unique\">\r\n                            <label class=\"custom-control-label\" fo" +
"r=\"unique\"style=\" position: initial;\">不重复</label>\r\n                        </div" +
">\r\n                    </div>\r\n                </div>\r\n                <div clas" +
"s=\"col-md-3\">\r\n                    <div class=\"form-group\">\r\n                   " +
"     <div class=\"custom-control custom-checkbox\">\r\n                            <" +
"input type=\"checkbox\" class=\"custom-control-input\" id=\"today\">\r\n                " +
"            <label class=\"custom-control-label\" for=\"today\"style=\" position: ini" +
"tial;\">今天</label>\r\n                        </div>\r\n                    </div>\r\n " +
"               </div>\r\n                <div class=\"col-md-3\">\r\n                 " +
"   <div class=\"form-group\">\r\n                        <div class=\"custom-control " +
"custom-checkbox\">\r\n                            <input type=\"checkbox\" class=\"cus" +
"tom-control-input\" id=\"hour\">\r\n                            <label class=\"custom-" +
"control-label\" for=\"hour\"style=\" position: initial;\">一小时</label>\r\n              " +
"          </div>\r\n                    </div>\r\n                </div>\r\n          " +
"  </div>\r\n            <div class=\"row\">\r\n                <div class=\"col-md-6\">\r" +
"\n                    <div class=\"form-group\">\r\n                        <label fo" +
"r=\"Message\" class=\"form-control-label\">Message</label>\r\n                        " +
"<input id=\"Message\" class=\"form-control\" placeholder=\"Message\">\r\n               " +
"     </div>\r\n                </div>\r\n                <div class=\"col-md-6\">\r\n   " +
"                 <div class=\"form-group\">\r\n                        <label for=\"L" +
"evel\" class=\"form-control-label\">日志级别</label>\r\n                        <select i" +
"d=\"Level\" class=\"form-control\">\r\n                            <option value=\"\">Al" +
"l</option>\r\n                            <option value=\"Trace\">Trace</option>\r\n  " +
"                          <option value=\"Debug\">Debug</option>\r\n                " +
"            <option value=\"Info\">Info</option>\r\n                            <opt" +
"ion value=\"Warn\">Warn</option>\r\n                            <option value=\"Error" +
"\">Error</option>\r\n                            <option value=\"Fatal\">Fatal</optio" +
"n>\r\n                        </select>\r\n                    </div>\r\n             " +
"   </div>\r\n            </div>\r\n            <div class=\"row\">\r\n                <d" +
"iv class=\"col-md-6\">\r\n                    <div class=\"form-group\">\r\n            " +
"            <label for=\"StartTime\" class=\"form-control-label\">开始时间</label>\r\n    " +
"                    <input type=\"text\" class=\"form-control datetimepicker-input\"" +
" id=\"StartTime\" data-toggle=\"datetimepicker\" data-target=\"#StartTime\" />\r\n      " +
"              </div>\r\n                </div>\r\n                <div class=\"col-md" +
"-6\">\r\n                    <div class=\"form-group\">\r\n                        <lab" +
"el for=\"EndTime\" class=\"form-control-label\">结束时间</label>\r\n                      " +
"  <input type=\"text\" class=\"form-control datetimepicker-input\" id=\"EndTime\" data" +
"-toggle=\"datetimepicker\" data-target=\"#EndTime\" />\r\n                    </div>\r\n" +
"                </div>\r\n            </div>\r\n            <button class=\"btn btn-o" +
"utline-primary\" id=\"searchBtn\">查询</button>\r\n        </form>\r\n\r\n    </div>\r\n    <" +
"div id=\"LogList\">\r\n        ");


            
            #line 89 "..\..\Views\Home\Basic.cshtml"
   Write(Raw(ViewData["logs"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div id=\"page\">\r\n        ");


            
            #line 92 "..\..\Views\Home\Basic.cshtml"
   Write(Raw(ViewData["page"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
